--clear data
TRUNCATE TABLE error.error_trace;

ALTER SEQUENCE error.error_trace_id_seq RESTART WITH 9;

--insert test data
INSERT INTO error.error_trace (id, document_id, date_occurred, error_type, occurred_at, stack_trace, status, record_id, date_closed, document_type, retry_url) VALUES (1, '85ed95b2-8436-4a93-9ae7-ab104d65edd7', '2018-03-14 07:53:11.152000', 'OPENMRS FAILED CLIENT PUSH', null, 'at sun.reflect.GeneratedMethodAccessor985.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
', null, null, null, 'org.opensrp.domain.Client', '');
INSERT INTO error.error_trace (id, document_id, date_occurred, error_type, occurred_at, stack_trace, status, record_id, date_closed, document_type, retry_url) VALUES (2, 'd41ba935-c8f6-4d3d-8432-8e8059ae39ca', '2018-03-14 11:24:30.643000', 'OPENMRS FAILED CLIENT PUSH', null, 'at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
', null, null, null, 'org.opensrp.domain.Client', '');
INSERT INTO error.error_trace (id, document_id, date_occurred, error_type, occurred_at, stack_trace, status, record_id, date_closed, document_type, retry_url) VALUES (3, 'f4bb0d37-0f08-44e2-822f-87d81983eefb', '2018-03-15 16:16:09.571000', 'OPENMRS FAILED EVENT PUSH', null, 'at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
', null, null, null, 'org.opensrp.domain.Event', '');
INSERT INTO error.error_trace (id, document_id, date_occurred, error_type, occurred_at, stack_trace, status, record_id, date_closed, document_type, retry_url) VALUES (4, '8798ae98-4f71-4bbb-8391-bfbda783b2d9', '2018-03-19 16:31:47.916000', 'OPENMRS FAILED CLIENT PUSH', null, 'at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
', null, null, null, 'org.opensrp.domain.Client', '');
INSERT INTO error.error_trace (id, document_id, date_occurred, error_type, occurred_at, stack_trace, status, record_id, date_closed, document_type, retry_url) VALUES (5, 'ea96c23d-bbf1-4365-bdf5-bcf56f08ce1f', '2018-03-22 15:59:30.791000', 'OPENMRS FAILED EVENT PUSH', null, 'at sun.reflect.GeneratedMethodAccessor985.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
', null, null, null, 'org.opensrp.domain.Event', '');
INSERT INTO error.error_trace (id, document_id, date_occurred, error_type, occurred_at, stack_trace, status, record_id, date_closed, document_type, retry_url) VALUES (6, '911c7520-f701-419e-b225-5e21286b585b', '2018-01-11 11:14:07.655000', 'OPENMRS FAILED EVENT VALIDATION', null, 'at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
', null, null, null, 'org.opensrp.domain.Event', '');
INSERT INTO error.error_trace (id, document_id, date_occurred, error_type, occurred_at, stack_trace, status, record_id, date_closed, document_type, retry_url) VALUES (7, '48106c03-8900-4156-a7bf-93226e1d3e58', '2018-01-03 11:20:52.467000', 'FormSubmissionProcessor', 'org.opensrp.service.formSubmission.FormSubmissionListener', '[Ljava.lang.StackTraceElement;@22cdbe2', 'solved', null, null, 'org.opensrp.form.domain.FormSubmission', null);
INSERT INTO error.error_trace (id, document_id, date_occurred, error_type, occurred_at, stack_trace, status, record_id, date_closed, document_type, retry_url) VALUES (8, '07c32814-d7d1-48a5-8320-ed80435a4606', '2018-01-03 17:06:11.166000', 'FormSubmissionProcessor', 'org.opensrp.service.formSubmission.FormSubmissionListener', '[Ljava.lang.StackTraceElement;@50ef4583', 'solved', null, null, 'org.opensrp.form.domain.FormSubmission', null);