INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe1'), (SELECT ID FROM report.dim_indicator WHERE indicator='OCP'), 12, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='OCP'), 12, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe3'), (SELECT ID FROM report.dim_indicator WHERE indicator='OCP'), 7, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='OCP'), 13, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe5'), (SELECT ID FROM report.dim_indicator WHERE indicator='OCP'), 10, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp1'), (SELECT ID FROM report.dim_indicator WHERE indicator='OCP'), 15, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp2'), (SELECT ID FROM report.dim_indicator WHERE indicator='OCP'), 11, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp3'), (SELECT ID FROM report.dim_indicator WHERE indicator='OCP'), 20, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp4'), (SELECT ID FROM report.dim_indicator WHERE indicator='OCP'), 10, '2012-03-26', '2013-03-25');

INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe1'), (SELECT ID FROM report.dim_indicator WHERE indicator='IUD'), 16, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='IUD'), 13, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe3'), (SELECT ID FROM report.dim_indicator WHERE indicator='IUD'), 11, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='IUD'), 15, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe5'), (SELECT ID FROM report.dim_indicator WHERE indicator='IUD'), 10, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp1'), (SELECT ID FROM report.dim_indicator WHERE indicator='IUD'), 17, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp2'), (SELECT ID FROM report.dim_indicator WHERE indicator='IUD'), 15, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp3'), (SELECT ID FROM report.dim_indicator WHERE indicator='IUD'), 20, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp4'), (SELECT ID FROM report.dim_indicator WHERE indicator='IUD'), 13, '2012-03-26', '2013-03-25');

INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe1'), (SELECT ID FROM report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 23, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 25, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe3'), (SELECT ID FROM report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 15, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 23, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe5'), (SELECT ID FROM report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 17, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp1'), (SELECT ID FROM report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 37, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp2'), (SELECT ID FROM report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 35, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp3'), (SELECT ID FROM report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 45, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp4'), (SELECT ID FROM report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 28, '2012-03-26', '2013-03-25');

INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe1'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC'), 60, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC'), 72, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe3'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC'), 39, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC'), 65, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe5'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC'), 48, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp1'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC'), 94, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp2'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC'), 65, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp3'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC'), 126, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp4'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC'), 63, '2012-03-26', '2013-03-25');

INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe1'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC<12'), 48, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC<12'), 58, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe3'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC<12'), 2, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC<12'), 52, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe5'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC<12'), 38, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp1'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC<12'), 78, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp2'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC<12'), 61, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp3'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC<12'), 90, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp4'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC<12'), 40, '2012-03-26', '2013-03-25');

INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe1'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC4'), 60, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC4'), 72, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe3'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC4'), 4, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC4'), 52, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe5'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC4'), 38, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp1'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC4'), 0, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp2'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC4'), 0, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp3'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC4'), 0, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp4'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC4'), 0, '2012-03-26', '2013-03-25');

INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe1'), (SELECT ID FROM report.dim_indicator WHERE indicator='SUB_TT'), 60, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='SUB_TT'), 72, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe3'), (SELECT ID FROM report.dim_indicator WHERE indicator='SUB_TT'), 39, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='SUB_TT'), 65, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe5'), (SELECT ID FROM report.dim_indicator WHERE indicator='SUB_TT'), 48, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp1'), (SELECT ID FROM report.dim_indicator WHERE indicator='SUB_TT'), 94, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp2'), (SELECT ID FROM report.dim_indicator WHERE indicator='SUB_TT'), 65, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp3'), (SELECT ID FROM report.dim_indicator WHERE indicator='SUB_TT'), 126, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp4'), (SELECT ID FROM report.dim_indicator WHERE indicator='SUB_TT'), 63, '2012-03-26', '2013-03-25');

INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe1'), (SELECT ID FROM report.dim_indicator WHERE indicator='BCG'), 53, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='BCG'), 63, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe3'), (SELECT ID FROM report.dim_indicator WHERE indicator='BCG'), 33, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='BCG'), 56, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe5'), (SELECT ID FROM report.dim_indicator WHERE indicator='BCG'), 41, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp1'), (SELECT ID FROM report.dim_indicator WHERE indicator='BCG'), 80, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp2'), (SELECT ID FROM report.dim_indicator WHERE indicator='BCG'), 65, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp3'), (SELECT ID FROM report.dim_indicator WHERE indicator='BCG'), 93, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp4'), (SELECT ID FROM report.dim_indicator WHERE indicator='BCG'), 57, '2012-03-26', '2013-03-25');

INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe1'), (SELECT ID FROM report.dim_indicator WHERE indicator='MEASLES'), 53, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='MEASLES'), 63, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe3'), (SELECT ID FROM report.dim_indicator WHERE indicator='MEASLES'), 33, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='MEASLES'), 56, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe5'), (SELECT ID FROM report.dim_indicator WHERE indicator='MEASLES'), 41, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp1'), (SELECT ID FROM report.dim_indicator WHERE indicator='MEASLES'), 80, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp2'), (SELECT ID FROM report.dim_indicator WHERE indicator='MEASLES'), 65, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp3'), (SELECT ID FROM report.dim_indicator WHERE indicator='MEASLES'), 93, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp4'), (SELECT ID FROM report.dim_indicator WHERE indicator='MEASLES'), 57, '2012-03-26', '2013-03-25');

INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe1'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 58, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 59, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe3'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 21, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 49, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe5'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 37, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp1'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 68, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp2'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 22, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp3'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 84, '2012-03-26', '2013-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='klp4'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 45, '2012-03-26', '2013-03-25');

