--Annual targets for 'bhe2'
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe2'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

--Annual targets for 'bhe4'
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='OCP'), 15, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='IUD'), 15, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 23, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 23, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC'), 62, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC<12'), 50, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='ANC4'), 62, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='SUB_TT'), 62, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='BCG'), 56, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT3_OPV3'), 56, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='MEASLES'), 56, '2013-03-26', '2014-03-25');
INSERT INTO report.annual_target (service_provider, indicator, target, start_date, end_date) VALUES ((SELECT sp.ID FROM report.dim_service_provider sp, report.dim_anm a WHERE sp.service_provider = a.id and anmIdentifier='bhe4'), (SELECT ID FROM report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 56, '2013-03-26', '2014-03-25');