INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Yalburga', (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'chc_mangalore'), 'mangalore_a', 'hirebindal' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Yalburga' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='chc_mangalore') AND subCenter='mangalore_a' AND village='hirebindal');
INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Yalburga', (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'chc_mangalore'), 'mangalore_a', 'kadralli' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Yalburga' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='chc_mangalore') AND subCenter='mangalore_a' AND village='kadralli');

INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Yalburga', (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'phc_mudhol'), 'mudhol', 'anganwadi_1' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Yalburga' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='phc_mudhol') AND subCenter='mudhol' AND village='anganwadi_1');
INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Yalburga', (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'phc_mudhol'), 'mudhol', 'anganwadi_2' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Yalburga' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='phc_mudhol') AND subCenter='mudhol' AND village='anganwadi_2');
INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Yalburga', (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'phc_mudhol'), 'mudhol', 'anganwadi_4' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Yalburga' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='phc_mudhol') AND subCenter='mudhol' AND village='anganwadi_4');
INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Yalburga', (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'phc_mudhol'), 'mudhol', 'anganwadi_5' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Yalburga' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='phc_mudhol') AND subCenter='mudhol' AND village='anganwadi_5');
INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Yalburga', (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'phc_mudhol'), 'mudhol', 'anganwadi_6' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Yalburga' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='phc_mudhol') AND subCenter='mudhol' AND village='anganwadi_6');
INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Yalburga', (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'phc_mudhol'), 'mudhol', 'anganwadi_7' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Yalburga' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='phc_mudhol') AND subCenter='mudhol' AND village='anganwadi_7');
INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Yalburga', (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'phc_mudhol'), 'mudhol', 'anganwadi_8' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Yalburga' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='phc_mudhol') AND subCenter='mudhol' AND village='anganwadi_8');
INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Yalburga', (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'phc_mudhol'), 'mudhol', 'anganwadi_9' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Yalburga' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='phc_mudhol') AND subCenter='mudhol' AND village='anganwadi_9');
INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Yalburga', (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'phc_mudhol'), 'mudhol', 'anganwadi_10' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Yalburga' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='phc_mudhol') AND subCenter='mudhol' AND village='anganwadi_10');

INSERT INTO report.dim_location (state, district, taluka, phc, subCenter, village) SELECT 'Karnataka', 'Koppal', 'Kustagi' , (SELECT ID FROM report.dim_phc WHERE phcIdentifier = 'chc_tawargera'), 'tawargera_a',	'anganwadi_9' WHERE NOT EXISTS (SELECT dim_location FROM report.dim_location WHERE state='Karnataka' AND district='Koppal' AND taluka='Kustagi' AND phc=(SELECT ID FROM report.dim_phc WHERE phcIdentifier='chc_tawargera') AND subCenter='tawargera_a' AND village='anganwadi_9');


