package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.ActionMetadata;
import org.opensrp.domain.postgres.ActionMetadataExample;
import org.apache.ibatis.session.RowBounds;

public interface ActionMetadataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	long countByExample(ActionMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int deleteByExample(ActionMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int insert(ActionMetadata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int insertSelective(ActionMetadata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	List<ActionMetadata> selectByExampleWithRowbounds(ActionMetadataExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	List<ActionMetadata> selectByExample(ActionMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	ActionMetadata selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByExampleSelective(@Param("record") ActionMetadata record, @Param("example") ActionMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByExample(@Param("record") ActionMetadata record, @Param("example") ActionMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByPrimaryKeySelective(ActionMetadata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByPrimaryKey(ActionMetadata record);
}