package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.Action;
import org.opensrp.domain.postgres.ActionExample;

public interface ActionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	long countByExample(ActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	int deleteByExample(ActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	int insert(Action record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	int insertSelective(Action record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	List<Action> selectByExample(ActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	Action selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	int updateByExampleSelective(@Param("record") Action record, @Param("example") ActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	int updateByExample(@Param("record") Action record, @Param("example") ActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	int updateByPrimaryKeySelective(Action record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.action
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	int updateByPrimaryKey(Action record);
}