package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.AppStateToken;
import org.opensrp.domain.postgres.AppStateTokenExample;

public interface AppStateTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.app_state_token
     *
     * @mbg.generated Mon Mar 12 18:42:21 EAT 2018
     */
    long countByExample(AppStateTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.app_state_token
     *
     * @mbg.generated Mon Mar 12 18:42:21 EAT 2018
     */
    int deleteByExample(AppStateTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.app_state_token
     *
     * @mbg.generated Mon Mar 12 18:42:21 EAT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.app_state_token
     *
     * @mbg.generated Mon Mar 12 18:42:21 EAT 2018
     */
    int insert(AppStateToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.app_state_token
     *
     * @mbg.generated Mon Mar 12 18:42:21 EAT 2018
     */
    int insertSelective(AppStateToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.app_state_token
     *
     * @mbg.generated Mon Mar 12 18:42:21 EAT 2018
     */
    List<AppStateToken> selectByExample(AppStateTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.app_state_token
     *
     * @mbg.generated Mon Mar 12 18:42:21 EAT 2018
     */
    AppStateToken selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.app_state_token
     *
     * @mbg.generated Mon Mar 12 18:42:21 EAT 2018
     */
    int updateByExampleSelective(@Param("record") AppStateToken record, @Param("example") AppStateTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.app_state_token
     *
     * @mbg.generated Mon Mar 12 18:42:21 EAT 2018
     */
    int updateByExample(@Param("record") AppStateToken record, @Param("example") AppStateTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.app_state_token
     *
     * @mbg.generated Mon Mar 12 18:42:21 EAT 2018
     */
    int updateByPrimaryKeySelective(AppStateToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.app_state_token
     *
     * @mbg.generated Mon Mar 12 18:42:21 EAT 2018
     */
    int updateByPrimaryKey(AppStateToken record);
}