package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.AppStateToken;
import org.opensrp.domain.postgres.AppStateTokenExample;
import org.apache.ibatis.session.RowBounds;

public interface AppStateTokenMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	long countByExample(AppStateTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int deleteByExample(AppStateTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int insert(AppStateToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int insertSelective(AppStateToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	List<AppStateToken> selectByExampleWithRowbounds(AppStateTokenExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	List<AppStateToken> selectByExample(AppStateTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	AppStateToken selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByExampleSelective(@Param("record") AppStateToken record, @Param("example") AppStateTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByExample(@Param("record") AppStateToken record, @Param("example") AppStateTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByPrimaryKeySelective(AppStateToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.app_state_token
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByPrimaryKey(AppStateToken record);
}