package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.ErrorTrace;
import org.opensrp.domain.postgres.ErrorTraceExample;
import org.apache.ibatis.session.RowBounds;

public interface ErrorTraceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	long countByExample(ErrorTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int deleteByExample(ErrorTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int insert(ErrorTrace record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int insertSelective(ErrorTrace record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	List<ErrorTrace> selectByExampleWithRowbounds(ErrorTraceExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	List<ErrorTrace> selectByExample(ErrorTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	ErrorTrace selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByExampleSelective(@Param("record") ErrorTrace record, @Param("example") ErrorTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByExample(@Param("record") ErrorTrace record, @Param("example") ErrorTraceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByPrimaryKeySelective(ErrorTrace record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByPrimaryKey(ErrorTrace record);
}