package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.EventMetadata;
import org.opensrp.domain.postgres.EventMetadataExample;
import org.apache.ibatis.session.RowBounds;

public interface EventMetadataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	long countByExample(EventMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int deleteByExample(EventMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int insert(EventMetadata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int insertSelective(EventMetadata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	List<EventMetadata> selectByExampleWithRowbounds(EventMetadataExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	List<EventMetadata> selectByExample(EventMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	EventMetadata selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByExampleSelective(@Param("record") EventMetadata record, @Param("example") EventMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByExample(@Param("record") EventMetadata record, @Param("example") EventMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByPrimaryKeySelective(EventMetadata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	int updateByPrimaryKey(EventMetadata record);
}