package org.opensrp.repository.postgres.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.ReportMetadata;
import org.opensrp.domain.postgres.ReportMetadataExample;

public interface ReportMetadataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.report_metadata
	 * @mbg.generated  Fri Mar 23 14:23:39 EAT 2018
	 */
	long countByExample(ReportMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.report_metadata
	 * @mbg.generated  Fri Mar 23 14:23:39 EAT 2018
	 */
	int deleteByExample(ReportMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.report_metadata
	 * @mbg.generated  Fri Mar 23 14:23:39 EAT 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.report_metadata
	 * @mbg.generated  Fri Mar 23 14:23:39 EAT 2018
	 */
	int insert(ReportMetadata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.report_metadata
	 * @mbg.generated  Fri Mar 23 14:23:39 EAT 2018
	 */
	int insertSelective(ReportMetadata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.report_metadata
	 * @mbg.generated  Fri Mar 23 14:23:39 EAT 2018
	 */
	List<ReportMetadata> selectByExample(ReportMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.report_metadata
	 * @mbg.generated  Fri Mar 23 14:23:39 EAT 2018
	 */
	ReportMetadata selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.report_metadata
	 * @mbg.generated  Fri Mar 23 14:23:39 EAT 2018
	 */
	int updateByExampleSelective(@Param("record") ReportMetadata record, @Param("example") ReportMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.report_metadata
	 * @mbg.generated  Fri Mar 23 14:23:39 EAT 2018
	 */
	int updateByExample(@Param("record") ReportMetadata record, @Param("example") ReportMetadataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.report_metadata
	 * @mbg.generated  Fri Mar 23 14:23:39 EAT 2018
	 */
	int updateByPrimaryKeySelective(ReportMetadata record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.report_metadata
	 * @mbg.generated  Fri Mar 23 14:23:39 EAT 2018
	 */
	int updateByPrimaryKey(ReportMetadata record);
}