package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.ViewConfiguration;
import org.opensrp.domain.postgres.ViewConfigurationExample;

public interface ViewConfigurationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.view_configuration
	 * @mbg.generated  Mon Apr 23 10:29:52 EAT 2018
	 */
	long countByExample(ViewConfigurationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.view_configuration
	 * @mbg.generated  Mon Apr 23 10:29:52 EAT 2018
	 */
	int deleteByExample(ViewConfigurationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.view_configuration
	 * @mbg.generated  Mon Apr 23 10:29:52 EAT 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.view_configuration
	 * @mbg.generated  Mon Apr 23 10:29:52 EAT 2018
	 */
	int insert(ViewConfiguration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.view_configuration
	 * @mbg.generated  Mon Apr 23 10:29:52 EAT 2018
	 */
	int insertSelective(ViewConfiguration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.view_configuration
	 * @mbg.generated  Mon Apr 23 10:29:52 EAT 2018
	 */
	List<ViewConfiguration> selectByExample(ViewConfigurationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.view_configuration
	 * @mbg.generated  Mon Apr 23 10:29:52 EAT 2018
	 */
	ViewConfiguration selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.view_configuration
	 * @mbg.generated  Mon Apr 23 10:29:52 EAT 2018
	 */
	int updateByExampleSelective(@Param("record") ViewConfiguration record,
	                             @Param("example") ViewConfigurationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.view_configuration
	 * @mbg.generated  Mon Apr 23 10:29:52 EAT 2018
	 */
	int updateByExample(@Param("record") ViewConfiguration record, @Param("example") ViewConfigurationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.view_configuration
	 * @mbg.generated  Mon Apr 23 10:29:52 EAT 2018
	 */
	int updateByPrimaryKeySelective(ViewConfiguration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.view_configuration
	 * @mbg.generated  Mon Apr 23 10:29:52 EAT 2018
	 */
	int updateByPrimaryKey(ViewConfiguration record);
}