package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.ViewConfigurationMetadata;
import org.opensrp.domain.postgres.ViewConfigurationMetadataExample;

public interface ViewConfigurationMetadataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.view_configuration_metadata
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    long countByExample(ViewConfigurationMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.view_configuration_metadata
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    int deleteByExample(ViewConfigurationMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.view_configuration_metadata
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.view_configuration_metadata
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    int insert(ViewConfigurationMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.view_configuration_metadata
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    int insertSelective(ViewConfigurationMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.view_configuration_metadata
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    List<ViewConfigurationMetadata> selectByExample(ViewConfigurationMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.view_configuration_metadata
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    ViewConfigurationMetadata selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.view_configuration_metadata
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    int updateByExampleSelective(@Param("record") ViewConfigurationMetadata record, @Param("example") ViewConfigurationMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.view_configuration_metadata
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    int updateByExample(@Param("record") ViewConfigurationMetadata record, @Param("example") ViewConfigurationMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.view_configuration_metadata
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    int updateByPrimaryKeySelective(ViewConfigurationMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.view_configuration_metadata
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    int updateByPrimaryKey(ViewConfigurationMetadata record);
}