-- Annual targets for 'trainer1'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

-- Annual targets for 'trainer2'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='trainer2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

-- Annual targets for 'user1'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user1'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

-- Annual targets for 'user2'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user2'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

-- Annual targets for 'user3'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user3'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

-- Annual targets for 'user4'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user4'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

-- Annual targets for 'user5'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user5'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

-- Annual targets for 'user6'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user6'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

-- Annual targets for 'user7'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user7'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

-- Annual targets for 'user8'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user8'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

-- Annual targets for 'user9'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user9'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');

-- Annual targets for 'user10'
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 13, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 24, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC4'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='SUB_TT'), 70, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT3_OPV3'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 63, '2013-03-26', '2014-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='user10'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 63, '2013-03-26', '2014-03-25');