package org.opensrp.common.monitor;

public enum Metric {
    REPORTING_ANM_REPORTS_CACHE_TIME,
    REPORTING_ANM_REPORTS_INSERT_TIME,
    REPORTING_SERVICE_PROVIDED_CACHE_TIME,
    REPORTING_SERVICE_PROVIDED_INSERT_TIME,
}
