package org.opensrp.domain.postgres;

public class AlertMetadata {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert_metadata.id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert_metadata.alert_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private Long alertId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert_metadata.base_entity_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private String baseEntityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert_metadata.server_version
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private Long serverVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert_metadata.provider_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private String providerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert_metadata.location_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private String locationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert_metadata.team
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private String team;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert_metadata.team_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private String teamId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert_metadata.is_active
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private Boolean isActive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert_metadata.trigger_name
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private String triggerName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert_metadata.id
	 * @return  the value of core.alert_metadata.id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert_metadata.id
	 * @param id  the value for core.alert_metadata.id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert_metadata.alert_id
	 * @return  the value of core.alert_metadata.alert_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public Long getAlertId() {
		return alertId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert_metadata.alert_id
	 * @param alertId  the value for core.alert_metadata.alert_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setAlertId(Long alertId) {
		this.alertId = alertId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert_metadata.base_entity_id
	 * @return  the value of core.alert_metadata.base_entity_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public String getBaseEntityId() {
		return baseEntityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert_metadata.base_entity_id
	 * @param baseEntityId  the value for core.alert_metadata.base_entity_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setBaseEntityId(String baseEntityId) {
		this.baseEntityId = baseEntityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert_metadata.server_version
	 * @return  the value of core.alert_metadata.server_version
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public Long getServerVersion() {
		return serverVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert_metadata.server_version
	 * @param serverVersion  the value for core.alert_metadata.server_version
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setServerVersion(Long serverVersion) {
		this.serverVersion = serverVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert_metadata.provider_id
	 * @return  the value of core.alert_metadata.provider_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public String getProviderId() {
		return providerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert_metadata.provider_id
	 * @param providerId  the value for core.alert_metadata.provider_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert_metadata.location_id
	 * @return  the value of core.alert_metadata.location_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public String getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert_metadata.location_id
	 * @param locationId  the value for core.alert_metadata.location_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert_metadata.team
	 * @return  the value of core.alert_metadata.team
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public String getTeam() {
		return team;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert_metadata.team
	 * @param team  the value for core.alert_metadata.team
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setTeam(String team) {
		this.team = team;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert_metadata.team_id
	 * @return  the value of core.alert_metadata.team_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public String getTeamId() {
		return teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert_metadata.team_id
	 * @param teamId  the value for core.alert_metadata.team_id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setTeamId(String teamId) {
		this.teamId = teamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert_metadata.is_active
	 * @return  the value of core.alert_metadata.is_active
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public Boolean getIsActive() {
		return isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert_metadata.is_active
	 * @param isActive  the value for core.alert_metadata.is_active
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert_metadata.trigger_name
	 * @return  the value of core.alert_metadata.trigger_name
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public String getTriggerName() {
		return triggerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert_metadata.trigger_name
	 * @param triggerName  the value for core.alert_metadata.trigger_name
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setTriggerName(String triggerName) {
		this.triggerName = triggerName;
	}
}