package org.opensrp.domain.postgres;

import java.util.ArrayList;
import java.util.List;

public class AlertMetadataExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	public AlertMetadataExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAlertIdIsNull() {
			addCriterion("alert_id is null");
			return (Criteria) this;
		}

		public Criteria andAlertIdIsNotNull() {
			addCriterion("alert_id is not null");
			return (Criteria) this;
		}

		public Criteria andAlertIdEqualTo(Long value) {
			addCriterion("alert_id =", value, "alertId");
			return (Criteria) this;
		}

		public Criteria andAlertIdNotEqualTo(Long value) {
			addCriterion("alert_id <>", value, "alertId");
			return (Criteria) this;
		}

		public Criteria andAlertIdGreaterThan(Long value) {
			addCriterion("alert_id >", value, "alertId");
			return (Criteria) this;
		}

		public Criteria andAlertIdGreaterThanOrEqualTo(Long value) {
			addCriterion("alert_id >=", value, "alertId");
			return (Criteria) this;
		}

		public Criteria andAlertIdLessThan(Long value) {
			addCriterion("alert_id <", value, "alertId");
			return (Criteria) this;
		}

		public Criteria andAlertIdLessThanOrEqualTo(Long value) {
			addCriterion("alert_id <=", value, "alertId");
			return (Criteria) this;
		}

		public Criteria andAlertIdIn(List<Long> values) {
			addCriterion("alert_id in", values, "alertId");
			return (Criteria) this;
		}

		public Criteria andAlertIdNotIn(List<Long> values) {
			addCriterion("alert_id not in", values, "alertId");
			return (Criteria) this;
		}

		public Criteria andAlertIdBetween(Long value1, Long value2) {
			addCriterion("alert_id between", value1, value2, "alertId");
			return (Criteria) this;
		}

		public Criteria andAlertIdNotBetween(Long value1, Long value2) {
			addCriterion("alert_id not between", value1, value2, "alertId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdIsNull() {
			addCriterion("base_entity_id is null");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdIsNotNull() {
			addCriterion("base_entity_id is not null");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdEqualTo(String value) {
			addCriterion("base_entity_id =", value, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdNotEqualTo(String value) {
			addCriterion("base_entity_id <>", value, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdGreaterThan(String value) {
			addCriterion("base_entity_id >", value, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdGreaterThanOrEqualTo(String value) {
			addCriterion("base_entity_id >=", value, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdLessThan(String value) {
			addCriterion("base_entity_id <", value, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdLessThanOrEqualTo(String value) {
			addCriterion("base_entity_id <=", value, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdLike(String value) {
			addCriterion("base_entity_id like", value, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdNotLike(String value) {
			addCriterion("base_entity_id not like", value, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdIn(List<String> values) {
			addCriterion("base_entity_id in", values, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdNotIn(List<String> values) {
			addCriterion("base_entity_id not in", values, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdBetween(String value1, String value2) {
			addCriterion("base_entity_id between", value1, value2, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andBaseEntityIdNotBetween(String value1, String value2) {
			addCriterion("base_entity_id not between", value1, value2, "baseEntityId");
			return (Criteria) this;
		}

		public Criteria andServerVersionIsNull() {
			addCriterion("server_version is null");
			return (Criteria) this;
		}

		public Criteria andServerVersionIsNotNull() {
			addCriterion("server_version is not null");
			return (Criteria) this;
		}

		public Criteria andServerVersionEqualTo(Long value) {
			addCriterion("server_version =", value, "serverVersion");
			return (Criteria) this;
		}

		public Criteria andServerVersionNotEqualTo(Long value) {
			addCriterion("server_version <>", value, "serverVersion");
			return (Criteria) this;
		}

		public Criteria andServerVersionGreaterThan(Long value) {
			addCriterion("server_version >", value, "serverVersion");
			return (Criteria) this;
		}

		public Criteria andServerVersionGreaterThanOrEqualTo(Long value) {
			addCriterion("server_version >=", value, "serverVersion");
			return (Criteria) this;
		}

		public Criteria andServerVersionLessThan(Long value) {
			addCriterion("server_version <", value, "serverVersion");
			return (Criteria) this;
		}

		public Criteria andServerVersionLessThanOrEqualTo(Long value) {
			addCriterion("server_version <=", value, "serverVersion");
			return (Criteria) this;
		}

		public Criteria andServerVersionIn(List<Long> values) {
			addCriterion("server_version in", values, "serverVersion");
			return (Criteria) this;
		}

		public Criteria andServerVersionNotIn(List<Long> values) {
			addCriterion("server_version not in", values, "serverVersion");
			return (Criteria) this;
		}

		public Criteria andServerVersionBetween(Long value1, Long value2) {
			addCriterion("server_version between", value1, value2, "serverVersion");
			return (Criteria) this;
		}

		public Criteria andServerVersionNotBetween(Long value1, Long value2) {
			addCriterion("server_version not between", value1, value2, "serverVersion");
			return (Criteria) this;
		}

		public Criteria andProviderIdIsNull() {
			addCriterion("provider_id is null");
			return (Criteria) this;
		}

		public Criteria andProviderIdIsNotNull() {
			addCriterion("provider_id is not null");
			return (Criteria) this;
		}

		public Criteria andProviderIdEqualTo(String value) {
			addCriterion("provider_id =", value, "providerId");
			return (Criteria) this;
		}

		public Criteria andProviderIdNotEqualTo(String value) {
			addCriterion("provider_id <>", value, "providerId");
			return (Criteria) this;
		}

		public Criteria andProviderIdGreaterThan(String value) {
			addCriterion("provider_id >", value, "providerId");
			return (Criteria) this;
		}

		public Criteria andProviderIdGreaterThanOrEqualTo(String value) {
			addCriterion("provider_id >=", value, "providerId");
			return (Criteria) this;
		}

		public Criteria andProviderIdLessThan(String value) {
			addCriterion("provider_id <", value, "providerId");
			return (Criteria) this;
		}

		public Criteria andProviderIdLessThanOrEqualTo(String value) {
			addCriterion("provider_id <=", value, "providerId");
			return (Criteria) this;
		}

		public Criteria andProviderIdLike(String value) {
			addCriterion("provider_id like", value, "providerId");
			return (Criteria) this;
		}

		public Criteria andProviderIdNotLike(String value) {
			addCriterion("provider_id not like", value, "providerId");
			return (Criteria) this;
		}

		public Criteria andProviderIdIn(List<String> values) {
			addCriterion("provider_id in", values, "providerId");
			return (Criteria) this;
		}

		public Criteria andProviderIdNotIn(List<String> values) {
			addCriterion("provider_id not in", values, "providerId");
			return (Criteria) this;
		}

		public Criteria andProviderIdBetween(String value1, String value2) {
			addCriterion("provider_id between", value1, value2, "providerId");
			return (Criteria) this;
		}

		public Criteria andProviderIdNotBetween(String value1, String value2) {
			addCriterion("provider_id not between", value1, value2, "providerId");
			return (Criteria) this;
		}

		public Criteria andLocationIdIsNull() {
			addCriterion("location_id is null");
			return (Criteria) this;
		}

		public Criteria andLocationIdIsNotNull() {
			addCriterion("location_id is not null");
			return (Criteria) this;
		}

		public Criteria andLocationIdEqualTo(String value) {
			addCriterion("location_id =", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdNotEqualTo(String value) {
			addCriterion("location_id <>", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdGreaterThan(String value) {
			addCriterion("location_id >", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdGreaterThanOrEqualTo(String value) {
			addCriterion("location_id >=", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdLessThan(String value) {
			addCriterion("location_id <", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdLessThanOrEqualTo(String value) {
			addCriterion("location_id <=", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdLike(String value) {
			addCriterion("location_id like", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdNotLike(String value) {
			addCriterion("location_id not like", value, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdIn(List<String> values) {
			addCriterion("location_id in", values, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdNotIn(List<String> values) {
			addCriterion("location_id not in", values, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdBetween(String value1, String value2) {
			addCriterion("location_id between", value1, value2, "locationId");
			return (Criteria) this;
		}

		public Criteria andLocationIdNotBetween(String value1, String value2) {
			addCriterion("location_id not between", value1, value2, "locationId");
			return (Criteria) this;
		}

		public Criteria andTeamIsNull() {
			addCriterion("team is null");
			return (Criteria) this;
		}

		public Criteria andTeamIsNotNull() {
			addCriterion("team is not null");
			return (Criteria) this;
		}

		public Criteria andTeamEqualTo(String value) {
			addCriterion("team =", value, "team");
			return (Criteria) this;
		}

		public Criteria andTeamNotEqualTo(String value) {
			addCriterion("team <>", value, "team");
			return (Criteria) this;
		}

		public Criteria andTeamGreaterThan(String value) {
			addCriterion("team >", value, "team");
			return (Criteria) this;
		}

		public Criteria andTeamGreaterThanOrEqualTo(String value) {
			addCriterion("team >=", value, "team");
			return (Criteria) this;
		}

		public Criteria andTeamLessThan(String value) {
			addCriterion("team <", value, "team");
			return (Criteria) this;
		}

		public Criteria andTeamLessThanOrEqualTo(String value) {
			addCriterion("team <=", value, "team");
			return (Criteria) this;
		}

		public Criteria andTeamLike(String value) {
			addCriterion("team like", value, "team");
			return (Criteria) this;
		}

		public Criteria andTeamNotLike(String value) {
			addCriterion("team not like", value, "team");
			return (Criteria) this;
		}

		public Criteria andTeamIn(List<String> values) {
			addCriterion("team in", values, "team");
			return (Criteria) this;
		}

		public Criteria andTeamNotIn(List<String> values) {
			addCriterion("team not in", values, "team");
			return (Criteria) this;
		}

		public Criteria andTeamBetween(String value1, String value2) {
			addCriterion("team between", value1, value2, "team");
			return (Criteria) this;
		}

		public Criteria andTeamNotBetween(String value1, String value2) {
			addCriterion("team not between", value1, value2, "team");
			return (Criteria) this;
		}

		public Criteria andTeamIdIsNull() {
			addCriterion("team_id is null");
			return (Criteria) this;
		}

		public Criteria andTeamIdIsNotNull() {
			addCriterion("team_id is not null");
			return (Criteria) this;
		}

		public Criteria andTeamIdEqualTo(String value) {
			addCriterion("team_id =", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotEqualTo(String value) {
			addCriterion("team_id <>", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdGreaterThan(String value) {
			addCriterion("team_id >", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdGreaterThanOrEqualTo(String value) {
			addCriterion("team_id >=", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdLessThan(String value) {
			addCriterion("team_id <", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdLessThanOrEqualTo(String value) {
			addCriterion("team_id <=", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdLike(String value) {
			addCriterion("team_id like", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotLike(String value) {
			addCriterion("team_id not like", value, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdIn(List<String> values) {
			addCriterion("team_id in", values, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotIn(List<String> values) {
			addCriterion("team_id not in", values, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdBetween(String value1, String value2) {
			addCriterion("team_id between", value1, value2, "teamId");
			return (Criteria) this;
		}

		public Criteria andTeamIdNotBetween(String value1, String value2) {
			addCriterion("team_id not between", value1, value2, "teamId");
			return (Criteria) this;
		}

		public Criteria andIsActiveIsNull() {
			addCriterion("is_active is null");
			return (Criteria) this;
		}

		public Criteria andIsActiveIsNotNull() {
			addCriterion("is_active is not null");
			return (Criteria) this;
		}

		public Criteria andIsActiveEqualTo(Boolean value) {
			addCriterion("is_active =", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotEqualTo(Boolean value) {
			addCriterion("is_active <>", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveGreaterThan(Boolean value) {
			addCriterion("is_active >", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_active >=", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveLessThan(Boolean value) {
			addCriterion("is_active <", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveLessThanOrEqualTo(Boolean value) {
			addCriterion("is_active <=", value, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveIn(List<Boolean> values) {
			addCriterion("is_active in", values, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotIn(List<Boolean> values) {
			addCriterion("is_active not in", values, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveBetween(Boolean value1, Boolean value2) {
			addCriterion("is_active between", value1, value2, "isActive");
			return (Criteria) this;
		}

		public Criteria andIsActiveNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_active not between", value1, value2, "isActive");
			return (Criteria) this;
		}

		public Criteria andTriggerNameIsNull() {
			addCriterion("trigger_name is null");
			return (Criteria) this;
		}

		public Criteria andTriggerNameIsNotNull() {
			addCriterion("trigger_name is not null");
			return (Criteria) this;
		}

		public Criteria andTriggerNameEqualTo(String value) {
			addCriterion("trigger_name =", value, "triggerName");
			return (Criteria) this;
		}

		public Criteria andTriggerNameNotEqualTo(String value) {
			addCriterion("trigger_name <>", value, "triggerName");
			return (Criteria) this;
		}

		public Criteria andTriggerNameGreaterThan(String value) {
			addCriterion("trigger_name >", value, "triggerName");
			return (Criteria) this;
		}

		public Criteria andTriggerNameGreaterThanOrEqualTo(String value) {
			addCriterion("trigger_name >=", value, "triggerName");
			return (Criteria) this;
		}

		public Criteria andTriggerNameLessThan(String value) {
			addCriterion("trigger_name <", value, "triggerName");
			return (Criteria) this;
		}

		public Criteria andTriggerNameLessThanOrEqualTo(String value) {
			addCriterion("trigger_name <=", value, "triggerName");
			return (Criteria) this;
		}

		public Criteria andTriggerNameLike(String value) {
			addCriterion("trigger_name like", value, "triggerName");
			return (Criteria) this;
		}

		public Criteria andTriggerNameNotLike(String value) {
			addCriterion("trigger_name not like", value, "triggerName");
			return (Criteria) this;
		}

		public Criteria andTriggerNameIn(List<String> values) {
			addCriterion("trigger_name in", values, "triggerName");
			return (Criteria) this;
		}

		public Criteria andTriggerNameNotIn(List<String> values) {
			addCriterion("trigger_name not in", values, "triggerName");
			return (Criteria) this;
		}

		public Criteria andTriggerNameBetween(String value1, String value2) {
			addCriterion("trigger_name between", value1, value2, "triggerName");
			return (Criteria) this;
		}

		public Criteria andTriggerNameNotBetween(String value1, String value2) {
			addCriterion("trigger_name not between", value1, value2, "triggerName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table core.alert_metadata
	 * @mbg.generated  Fri Mar 09 18:05:46 EAT 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.alert_metadata
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 09 15:24:01 EAT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}