package org.opensrp.domain.postgres;

public class Alert {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert.id
	 * @mbg.generated  Thu Mar 22 17:10:48 EAT 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.alert.json
	 * @mbg.generated  Thu Mar 22 17:10:48 EAT 2018
	 */
	private Object json;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert.id
	 * @return  the value of core.alert.id
	 * @mbg.generated  Thu Mar 22 17:10:48 EAT 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert.id
	 * @param id  the value for core.alert.id
	 * @mbg.generated  Thu Mar 22 17:10:48 EAT 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.alert.json
	 * @return  the value of core.alert.json
	 * @mbg.generated  Thu Mar 22 17:10:48 EAT 2018
	 */
	public Object getJson() {
		return json;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.alert.json
	 * @param json  the value for core.alert.json
	 * @mbg.generated  Thu Mar 22 17:10:48 EAT 2018
	 */
	public void setJson(Object json) {
		this.json = json;
	}
}