package org.opensrp.domain.postgres;

public class AppStateToken {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.app_state_token.id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.app_state_token.name
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.app_state_token.description
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.app_state_token.value
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.app_state_token.last_edited_date
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	private Long lastEditedDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.app_state_token.id
	 * @return  the value of core.app_state_token.id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.app_state_token.id
	 * @param id  the value for core.app_state_token.id
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.app_state_token.name
	 * @return  the value of core.app_state_token.name
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.app_state_token.name
	 * @param name  the value for core.app_state_token.name
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.app_state_token.description
	 * @return  the value of core.app_state_token.description
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.app_state_token.description
	 * @param description  the value for core.app_state_token.description
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.app_state_token.value
	 * @return  the value of core.app_state_token.value
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.app_state_token.value
	 * @param value  the value for core.app_state_token.value
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.app_state_token.last_edited_date
	 * @return  the value of core.app_state_token.last_edited_date
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public Long getLastEditedDate() {
		return lastEditedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.app_state_token.last_edited_date
	 * @param lastEditedDate  the value for core.app_state_token.last_edited_date
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setLastEditedDate(Long lastEditedDate) {
		this.lastEditedDate = lastEditedDate;
	}
}