package org.opensrp.domain.postgres;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ErrorTraceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	public ErrorTraceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	protected abstract static class GeneratedCriteria {
		
		protected List<Criterion> criteria;
		
		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}
		
		public boolean isValid() {
			return criteria.size() > 0;
		}
		
		public List<Criterion> getAllCriteria() {
			return criteria;
		}
		
		public List<Criterion> getCriteria() {
			return criteria;
		}
		
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}
		
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}
		
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}
		
		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}
		
		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}
		
		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}
		
		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}
		
		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}
		
		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdIsNull() {
			addCriterion("document_id is null");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdIsNotNull() {
			addCriterion("document_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdEqualTo(String value) {
			addCriterion("document_id =", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdNotEqualTo(String value) {
			addCriterion("document_id <>", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdGreaterThan(String value) {
			addCriterion("document_id >", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdGreaterThanOrEqualTo(String value) {
			addCriterion("document_id >=", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdLessThan(String value) {
			addCriterion("document_id <", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdLessThanOrEqualTo(String value) {
			addCriterion("document_id <=", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdLike(String value) {
			addCriterion("document_id like", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdNotLike(String value) {
			addCriterion("document_id not like", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdIn(List<String> values) {
			addCriterion("document_id in", values, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdNotIn(List<String> values) {
			addCriterion("document_id not in", values, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdBetween(String value1, String value2) {
			addCriterion("document_id between", value1, value2, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdNotBetween(String value1, String value2) {
			addCriterion("document_id not between", value1, value2, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredIsNull() {
			addCriterion("date_occurred is null");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredIsNotNull() {
			addCriterion("date_occurred is not null");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredEqualTo(Date value) {
			addCriterionForJDBCDate("date_occurred =", value, "dateOccurred");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredNotEqualTo(Date value) {
			addCriterionForJDBCDate("date_occurred <>", value, "dateOccurred");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredGreaterThan(Date value) {
			addCriterionForJDBCDate("date_occurred >", value, "dateOccurred");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("date_occurred >=", value, "dateOccurred");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredLessThan(Date value) {
			addCriterionForJDBCDate("date_occurred <", value, "dateOccurred");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("date_occurred <=", value, "dateOccurred");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredIn(List<Date> values) {
			addCriterionForJDBCDate("date_occurred in", values, "dateOccurred");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredNotIn(List<Date> values) {
			addCriterionForJDBCDate("date_occurred not in", values, "dateOccurred");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("date_occurred between", value1, value2, "dateOccurred");
			return (Criteria) this;
		}
		
		public Criteria andDateOccurredNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("date_occurred not between", value1, value2, "dateOccurred");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeIsNull() {
			addCriterion("error_type is null");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeIsNotNull() {
			addCriterion("error_type is not null");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeEqualTo(String value) {
			addCriterion("error_type =", value, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeNotEqualTo(String value) {
			addCriterion("error_type <>", value, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeGreaterThan(String value) {
			addCriterion("error_type >", value, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeGreaterThanOrEqualTo(String value) {
			addCriterion("error_type >=", value, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeLessThan(String value) {
			addCriterion("error_type <", value, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeLessThanOrEqualTo(String value) {
			addCriterion("error_type <=", value, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeLike(String value) {
			addCriterion("error_type like", value, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeNotLike(String value) {
			addCriterion("error_type not like", value, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeIn(List<String> values) {
			addCriterion("error_type in", values, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeNotIn(List<String> values) {
			addCriterion("error_type not in", values, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeBetween(String value1, String value2) {
			addCriterion("error_type between", value1, value2, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andErrorTypeNotBetween(String value1, String value2) {
			addCriterion("error_type not between", value1, value2, "errorType");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtIsNull() {
			addCriterion("occurred_at is null");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtIsNotNull() {
			addCriterion("occurred_at is not null");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtEqualTo(String value) {
			addCriterion("occurred_at =", value, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtNotEqualTo(String value) {
			addCriterion("occurred_at <>", value, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtGreaterThan(String value) {
			addCriterion("occurred_at >", value, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtGreaterThanOrEqualTo(String value) {
			addCriterion("occurred_at >=", value, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtLessThan(String value) {
			addCriterion("occurred_at <", value, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtLessThanOrEqualTo(String value) {
			addCriterion("occurred_at <=", value, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtLike(String value) {
			addCriterion("occurred_at like", value, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtNotLike(String value) {
			addCriterion("occurred_at not like", value, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtIn(List<String> values) {
			addCriterion("occurred_at in", values, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtNotIn(List<String> values) {
			addCriterion("occurred_at not in", values, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtBetween(String value1, String value2) {
			addCriterion("occurred_at between", value1, value2, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andOccurredAtNotBetween(String value1, String value2) {
			addCriterion("occurred_at not between", value1, value2, "occurredAt");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceIsNull() {
			addCriterion("stack_trace is null");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceIsNotNull() {
			addCriterion("stack_trace is not null");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceEqualTo(String value) {
			addCriterion("stack_trace =", value, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceNotEqualTo(String value) {
			addCriterion("stack_trace <>", value, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceGreaterThan(String value) {
			addCriterion("stack_trace >", value, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceGreaterThanOrEqualTo(String value) {
			addCriterion("stack_trace >=", value, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceLessThan(String value) {
			addCriterion("stack_trace <", value, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceLessThanOrEqualTo(String value) {
			addCriterion("stack_trace <=", value, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceLike(String value) {
			addCriterion("stack_trace like", value, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceNotLike(String value) {
			addCriterion("stack_trace not like", value, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceIn(List<String> values) {
			addCriterion("stack_trace in", values, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceNotIn(List<String> values) {
			addCriterion("stack_trace not in", values, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceBetween(String value1, String value2) {
			addCriterion("stack_trace between", value1, value2, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStackTraceNotBetween(String value1, String value2) {
			addCriterion("stack_trace not between", value1, value2, "stackTrace");
			return (Criteria) this;
		}
		
		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}
		
		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}
		
		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}
		
		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}
		
		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}
		
		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}
		
		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}
		
		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}
		
		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}
		
		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}
		
		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}
		
		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}
		
		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}
		
		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdIsNull() {
			addCriterion("record_id is null");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdIsNotNull() {
			addCriterion("record_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdEqualTo(String value) {
			addCriterion("record_id =", value, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdNotEqualTo(String value) {
			addCriterion("record_id <>", value, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdGreaterThan(String value) {
			addCriterion("record_id >", value, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdGreaterThanOrEqualTo(String value) {
			addCriterion("record_id >=", value, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdLessThan(String value) {
			addCriterion("record_id <", value, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdLessThanOrEqualTo(String value) {
			addCriterion("record_id <=", value, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdLike(String value) {
			addCriterion("record_id like", value, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdNotLike(String value) {
			addCriterion("record_id not like", value, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdIn(List<String> values) {
			addCriterion("record_id in", values, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdNotIn(List<String> values) {
			addCriterion("record_id not in", values, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdBetween(String value1, String value2) {
			addCriterion("record_id between", value1, value2, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andRecordIdNotBetween(String value1, String value2) {
			addCriterion("record_id not between", value1, value2, "recordId");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedIsNull() {
			addCriterion("date_closed is null");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedIsNotNull() {
			addCriterion("date_closed is not null");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedEqualTo(Date value) {
			addCriterionForJDBCDate("date_closed =", value, "dateClosed");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedNotEqualTo(Date value) {
			addCriterionForJDBCDate("date_closed <>", value, "dateClosed");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedGreaterThan(Date value) {
			addCriterionForJDBCDate("date_closed >", value, "dateClosed");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("date_closed >=", value, "dateClosed");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedLessThan(Date value) {
			addCriterionForJDBCDate("date_closed <", value, "dateClosed");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("date_closed <=", value, "dateClosed");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedIn(List<Date> values) {
			addCriterionForJDBCDate("date_closed in", values, "dateClosed");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedNotIn(List<Date> values) {
			addCriterionForJDBCDate("date_closed not in", values, "dateClosed");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("date_closed between", value1, value2, "dateClosed");
			return (Criteria) this;
		}
		
		public Criteria andDateClosedNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("date_closed not between", value1, value2, "dateClosed");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeIsNull() {
			addCriterion("document_type is null");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeIsNotNull() {
			addCriterion("document_type is not null");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeEqualTo(String value) {
			addCriterion("document_type =", value, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeNotEqualTo(String value) {
			addCriterion("document_type <>", value, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeGreaterThan(String value) {
			addCriterion("document_type >", value, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeGreaterThanOrEqualTo(String value) {
			addCriterion("document_type >=", value, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeLessThan(String value) {
			addCriterion("document_type <", value, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeLessThanOrEqualTo(String value) {
			addCriterion("document_type <=", value, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeLike(String value) {
			addCriterion("document_type like", value, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeNotLike(String value) {
			addCriterion("document_type not like", value, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeIn(List<String> values) {
			addCriterion("document_type in", values, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeNotIn(List<String> values) {
			addCriterion("document_type not in", values, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeBetween(String value1, String value2) {
			addCriterion("document_type between", value1, value2, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andDocumentTypeNotBetween(String value1, String value2) {
			addCriterion("document_type not between", value1, value2, "documentType");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlIsNull() {
			addCriterion("retry_url is null");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlIsNotNull() {
			addCriterion("retry_url is not null");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlEqualTo(String value) {
			addCriterion("retry_url =", value, "retryUrl");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlNotEqualTo(String value) {
			addCriterion("retry_url <>", value, "retryUrl");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlGreaterThan(String value) {
			addCriterion("retry_url >", value, "retryUrl");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlGreaterThanOrEqualTo(String value) {
			addCriterion("retry_url >=", value, "retryUrl");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlLessThan(String value) {
			addCriterion("retry_url <", value, "retryUrl");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlLessThanOrEqualTo(String value) {
			addCriterion("retry_url <=", value, "retryUrl");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlLike(String value) {
			addCriterion("retry_url like", value, "retryUrl");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlNotLike(String value) {
			addCriterion("retry_url not like", value, "retryUrl");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlIn(List<String> values) {
			addCriterion("retry_url in", values, "retryUrl");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlNotIn(List<String> values) {
			addCriterion("retry_url not in", values, "retryUrl");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlBetween(String value1, String value2) {
			addCriterion("retry_url between", value1, value2, "retryUrl");
			return (Criteria) this;
		}
		
		public Criteria andRetryUrlNotBetween(String value1, String value2) {
			addCriterion("retry_url not between", value1, value2, "retryUrl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table error.error_trace
	 * @mbg.generated  Tue Mar 27 11:36:08 EAT 2018
	 */
	public static class Criterion {
		
		private String condition;
		
		private Object value;
		
		private Object secondValue;
		
		private boolean noValue;
		
		private boolean singleValue;
		
		private boolean betweenValue;
		
		private boolean listValue;
		
		private String typeHandler;
		
		public String getCondition() {
			return condition;
		}
		
		public Object getValue() {
			return value;
		}
		
		public Object getSecondValue() {
			return secondValue;
		}
		
		public boolean isNoValue() {
			return noValue;
		}
		
		public boolean isSingleValue() {
			return singleValue;
		}
		
		public boolean isBetweenValue() {
			return betweenValue;
		}
		
		public boolean isListValue() {
			return listValue;
		}
		
		public String getTypeHandler() {
			return typeHandler;
		}
		
		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}
		
		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}
		
		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}
		
		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}
		
		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table error.error_trace
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 09 18:05:46 EAT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}