package org.opensrp.domain.postgres;

import java.util.Date;

public class ErrorTrace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.error_trace.id
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.error_trace.date_occurred
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    private Date dateOccurred;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.error_trace.error_type
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    private String errorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.error_trace.occurred_at
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    private String occurredAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.error_trace.stack_trace
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    private String stackTrace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.error_trace.status
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.error_trace.record_id
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.error_trace.date_closed
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    private Date dateClosed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.error_trace.document_type
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    private String documentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.error_trace.retry_url
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    private String retryUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.error_trace.id
     *
     * @return the value of error.error_trace.id
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.error_trace.id
     *
     * @param id the value for error.error_trace.id
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.error_trace.date_occurred
     *
     * @return the value of error.error_trace.date_occurred
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public Date getDateOccurred() {
        return dateOccurred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.error_trace.date_occurred
     *
     * @param dateOccurred the value for error.error_trace.date_occurred
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public void setDateOccurred(Date dateOccurred) {
        this.dateOccurred = dateOccurred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.error_trace.error_type
     *
     * @return the value of error.error_trace.error_type
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public String getErrorType() {
        return errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.error_trace.error_type
     *
     * @param errorType the value for error.error_trace.error_type
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public void setErrorType(String errorType) {
        this.errorType = errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.error_trace.occurred_at
     *
     * @return the value of error.error_trace.occurred_at
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public String getOccurredAt() {
        return occurredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.error_trace.occurred_at
     *
     * @param occurredAt the value for error.error_trace.occurred_at
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public void setOccurredAt(String occurredAt) {
        this.occurredAt = occurredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.error_trace.stack_trace
     *
     * @return the value of error.error_trace.stack_trace
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public String getStackTrace() {
        return stackTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.error_trace.stack_trace
     *
     * @param stackTrace the value for error.error_trace.stack_trace
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public void setStackTrace(String stackTrace) {
        this.stackTrace = stackTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.error_trace.status
     *
     * @return the value of error.error_trace.status
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.error_trace.status
     *
     * @param status the value for error.error_trace.status
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.error_trace.record_id
     *
     * @return the value of error.error_trace.record_id
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.error_trace.record_id
     *
     * @param recordId the value for error.error_trace.record_id
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.error_trace.date_closed
     *
     * @return the value of error.error_trace.date_closed
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public Date getDateClosed() {
        return dateClosed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.error_trace.date_closed
     *
     * @param dateClosed the value for error.error_trace.date_closed
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public void setDateClosed(Date dateClosed) {
        this.dateClosed = dateClosed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.error_trace.document_type
     *
     * @return the value of error.error_trace.document_type
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.error_trace.document_type
     *
     * @param documentType the value for error.error_trace.document_type
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.error_trace.retry_url
     *
     * @return the value of error.error_trace.retry_url
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public String getRetryUrl() {
        return retryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.error_trace.retry_url
     *
     * @param retryUrl the value for error.error_trace.retry_url
     *
     * @mbg.generated Fri Mar 09 18:05:46 EAT 2018
     */
    public void setRetryUrl(String retryUrl) {
        this.retryUrl = retryUrl;
    }
}