package org.opensrp.domain.postgres;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EventMetadataExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	public EventMetadataExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	protected abstract static class GeneratedCriteria {
		
		protected List<Criterion> criteria;
		
		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}
		
		public boolean isValid() {
			return criteria.size() > 0;
		}
		
		public List<Criterion> getAllCriteria() {
			return criteria;
		}
		
		public List<Criterion> getCriteria() {
			return criteria;
		}
		
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}
		
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}
		
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}
		
		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}
		
		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}
		
		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}
		
		public Criteria andEventIdIsNull() {
			addCriterion("event_id is null");
			return (Criteria) this;
		}
		
		public Criteria andEventIdIsNotNull() {
			addCriterion("event_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andEventIdEqualTo(Long value) {
			addCriterion("event_id =", value, "eventId");
			return (Criteria) this;
		}
		
		public Criteria andEventIdNotEqualTo(Long value) {
			addCriterion("event_id <>", value, "eventId");
			return (Criteria) this;
		}
		
		public Criteria andEventIdGreaterThan(Long value) {
			addCriterion("event_id >", value, "eventId");
			return (Criteria) this;
		}
		
		public Criteria andEventIdGreaterThanOrEqualTo(Long value) {
			addCriterion("event_id >=", value, "eventId");
			return (Criteria) this;
		}
		
		public Criteria andEventIdLessThan(Long value) {
			addCriterion("event_id <", value, "eventId");
			return (Criteria) this;
		}
		
		public Criteria andEventIdLessThanOrEqualTo(Long value) {
			addCriterion("event_id <=", value, "eventId");
			return (Criteria) this;
		}
		
		public Criteria andEventIdIn(List<Long> values) {
			addCriterion("event_id in", values, "eventId");
			return (Criteria) this;
		}
		
		public Criteria andEventIdNotIn(List<Long> values) {
			addCriterion("event_id not in", values, "eventId");
			return (Criteria) this;
		}
		
		public Criteria andEventIdBetween(Long value1, Long value2) {
			addCriterion("event_id between", value1, value2, "eventId");
			return (Criteria) this;
		}
		
		public Criteria andEventIdNotBetween(Long value1, Long value2) {
			addCriterion("event_id not between", value1, value2, "eventId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdIsNull() {
			addCriterion("document_id is null");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdIsNotNull() {
			addCriterion("document_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdEqualTo(String value) {
			addCriterion("document_id =", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdNotEqualTo(String value) {
			addCriterion("document_id <>", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdGreaterThan(String value) {
			addCriterion("document_id >", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdGreaterThanOrEqualTo(String value) {
			addCriterion("document_id >=", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdLessThan(String value) {
			addCriterion("document_id <", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdLessThanOrEqualTo(String value) {
			addCriterion("document_id <=", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdLike(String value) {
			addCriterion("document_id like", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdNotLike(String value) {
			addCriterion("document_id not like", value, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdIn(List<String> values) {
			addCriterion("document_id in", values, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdNotIn(List<String> values) {
			addCriterion("document_id not in", values, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdBetween(String value1, String value2) {
			addCriterion("document_id between", value1, value2, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andDocumentIdNotBetween(String value1, String value2) {
			addCriterion("document_id not between", value1, value2, "documentId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdIsNull() {
			addCriterion("base_entity_id is null");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdIsNotNull() {
			addCriterion("base_entity_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdEqualTo(String value) {
			addCriterion("base_entity_id =", value, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdNotEqualTo(String value) {
			addCriterion("base_entity_id <>", value, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdGreaterThan(String value) {
			addCriterion("base_entity_id >", value, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdGreaterThanOrEqualTo(String value) {
			addCriterion("base_entity_id >=", value, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdLessThan(String value) {
			addCriterion("base_entity_id <", value, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdLessThanOrEqualTo(String value) {
			addCriterion("base_entity_id <=", value, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdLike(String value) {
			addCriterion("base_entity_id like", value, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdNotLike(String value) {
			addCriterion("base_entity_id not like", value, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdIn(List<String> values) {
			addCriterion("base_entity_id in", values, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdNotIn(List<String> values) {
			addCriterion("base_entity_id not in", values, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdBetween(String value1, String value2) {
			addCriterion("base_entity_id between", value1, value2, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andBaseEntityIdNotBetween(String value1, String value2) {
			addCriterion("base_entity_id not between", value1, value2, "baseEntityId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdIsNull() {
			addCriterion("form_submission_id is null");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdIsNotNull() {
			addCriterion("form_submission_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdEqualTo(String value) {
			addCriterion("form_submission_id =", value, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdNotEqualTo(String value) {
			addCriterion("form_submission_id <>", value, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdGreaterThan(String value) {
			addCriterion("form_submission_id >", value, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdGreaterThanOrEqualTo(String value) {
			addCriterion("form_submission_id >=", value, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdLessThan(String value) {
			addCriterion("form_submission_id <", value, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdLessThanOrEqualTo(String value) {
			addCriterion("form_submission_id <=", value, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdLike(String value) {
			addCriterion("form_submission_id like", value, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdNotLike(String value) {
			addCriterion("form_submission_id not like", value, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdIn(List<String> values) {
			addCriterion("form_submission_id in", values, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdNotIn(List<String> values) {
			addCriterion("form_submission_id not in", values, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdBetween(String value1, String value2) {
			addCriterion("form_submission_id between", value1, value2, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andFormSubmissionIdNotBetween(String value1, String value2) {
			addCriterion("form_submission_id not between", value1, value2, "formSubmissionId");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionIsNull() {
			addCriterion("server_version is null");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionIsNotNull() {
			addCriterion("server_version is not null");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionEqualTo(Long value) {
			addCriterion("server_version =", value, "serverVersion");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionNotEqualTo(Long value) {
			addCriterion("server_version <>", value, "serverVersion");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionGreaterThan(Long value) {
			addCriterion("server_version >", value, "serverVersion");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionGreaterThanOrEqualTo(Long value) {
			addCriterion("server_version >=", value, "serverVersion");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionLessThan(Long value) {
			addCriterion("server_version <", value, "serverVersion");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionLessThanOrEqualTo(Long value) {
			addCriterion("server_version <=", value, "serverVersion");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionIn(List<Long> values) {
			addCriterion("server_version in", values, "serverVersion");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionNotIn(List<Long> values) {
			addCriterion("server_version not in", values, "serverVersion");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionBetween(Long value1, Long value2) {
			addCriterion("server_version between", value1, value2, "serverVersion");
			return (Criteria) this;
		}
		
		public Criteria andServerVersionNotBetween(Long value1, Long value2) {
			addCriterion("server_version not between", value1, value2, "serverVersion");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidIsNull() {
			addCriterion("openmrs_uuid is null");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidIsNotNull() {
			addCriterion("openmrs_uuid is not null");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidEqualTo(String value) {
			addCriterion("openmrs_uuid =", value, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidNotEqualTo(String value) {
			addCriterion("openmrs_uuid <>", value, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidGreaterThan(String value) {
			addCriterion("openmrs_uuid >", value, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidGreaterThanOrEqualTo(String value) {
			addCriterion("openmrs_uuid >=", value, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidLessThan(String value) {
			addCriterion("openmrs_uuid <", value, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidLessThanOrEqualTo(String value) {
			addCriterion("openmrs_uuid <=", value, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidLike(String value) {
			addCriterion("openmrs_uuid like", value, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidNotLike(String value) {
			addCriterion("openmrs_uuid not like", value, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidIn(List<String> values) {
			addCriterion("openmrs_uuid in", values, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidNotIn(List<String> values) {
			addCriterion("openmrs_uuid not in", values, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidBetween(String value1, String value2) {
			addCriterion("openmrs_uuid between", value1, value2, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andOpenmrsUuidNotBetween(String value1, String value2) {
			addCriterion("openmrs_uuid not between", value1, value2, "openmrsUuid");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeIsNull() {
			addCriterion("event_type is null");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeIsNotNull() {
			addCriterion("event_type is not null");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeEqualTo(String value) {
			addCriterion("event_type =", value, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeNotEqualTo(String value) {
			addCriterion("event_type <>", value, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeGreaterThan(String value) {
			addCriterion("event_type >", value, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeGreaterThanOrEqualTo(String value) {
			addCriterion("event_type >=", value, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeLessThan(String value) {
			addCriterion("event_type <", value, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeLessThanOrEqualTo(String value) {
			addCriterion("event_type <=", value, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeLike(String value) {
			addCriterion("event_type like", value, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeNotLike(String value) {
			addCriterion("event_type not like", value, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeIn(List<String> values) {
			addCriterion("event_type in", values, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeNotIn(List<String> values) {
			addCriterion("event_type not in", values, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeBetween(String value1, String value2) {
			addCriterion("event_type between", value1, value2, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventTypeNotBetween(String value1, String value2) {
			addCriterion("event_type not between", value1, value2, "eventType");
			return (Criteria) this;
		}
		
		public Criteria andEventDateIsNull() {
			addCriterion("event_date is null");
			return (Criteria) this;
		}
		
		public Criteria andEventDateIsNotNull() {
			addCriterion("event_date is not null");
			return (Criteria) this;
		}
		
		public Criteria andEventDateEqualTo(Date value) {
			addCriterion("event_date =", value, "eventDate");
			return (Criteria) this;
		}
		
		public Criteria andEventDateNotEqualTo(Date value) {
			addCriterion("event_date <>", value, "eventDate");
			return (Criteria) this;
		}
		
		public Criteria andEventDateGreaterThan(Date value) {
			addCriterion("event_date >", value, "eventDate");
			return (Criteria) this;
		}
		
		public Criteria andEventDateGreaterThanOrEqualTo(Date value) {
			addCriterion("event_date >=", value, "eventDate");
			return (Criteria) this;
		}
		
		public Criteria andEventDateLessThan(Date value) {
			addCriterion("event_date <", value, "eventDate");
			return (Criteria) this;
		}
		
		public Criteria andEventDateLessThanOrEqualTo(Date value) {
			addCriterion("event_date <=", value, "eventDate");
			return (Criteria) this;
		}
		
		public Criteria andEventDateIn(List<Date> values) {
			addCriterion("event_date in", values, "eventDate");
			return (Criteria) this;
		}
		
		public Criteria andEventDateNotIn(List<Date> values) {
			addCriterion("event_date not in", values, "eventDate");
			return (Criteria) this;
		}
		
		public Criteria andEventDateBetween(Date value1, Date value2) {
			addCriterion("event_date between", value1, value2, "eventDate");
			return (Criteria) this;
		}
		
		public Criteria andEventDateNotBetween(Date value1, Date value2) {
			addCriterion("event_date not between", value1, value2, "eventDate");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeIsNull() {
			addCriterion("entity_type is null");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeIsNotNull() {
			addCriterion("entity_type is not null");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeEqualTo(String value) {
			addCriterion("entity_type =", value, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeNotEqualTo(String value) {
			addCriterion("entity_type <>", value, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeGreaterThan(String value) {
			addCriterion("entity_type >", value, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeGreaterThanOrEqualTo(String value) {
			addCriterion("entity_type >=", value, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeLessThan(String value) {
			addCriterion("entity_type <", value, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeLessThanOrEqualTo(String value) {
			addCriterion("entity_type <=", value, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeLike(String value) {
			addCriterion("entity_type like", value, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeNotLike(String value) {
			addCriterion("entity_type not like", value, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeIn(List<String> values) {
			addCriterion("entity_type in", values, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeNotIn(List<String> values) {
			addCriterion("entity_type not in", values, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeBetween(String value1, String value2) {
			addCriterion("entity_type between", value1, value2, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andEntityTypeNotBetween(String value1, String value2) {
			addCriterion("entity_type not between", value1, value2, "entityType");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdIsNull() {
			addCriterion("provider_id is null");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdIsNotNull() {
			addCriterion("provider_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdEqualTo(String value) {
			addCriterion("provider_id =", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdNotEqualTo(String value) {
			addCriterion("provider_id <>", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdGreaterThan(String value) {
			addCriterion("provider_id >", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdGreaterThanOrEqualTo(String value) {
			addCriterion("provider_id >=", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdLessThan(String value) {
			addCriterion("provider_id <", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdLessThanOrEqualTo(String value) {
			addCriterion("provider_id <=", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdLike(String value) {
			addCriterion("provider_id like", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdNotLike(String value) {
			addCriterion("provider_id not like", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdIn(List<String> values) {
			addCriterion("provider_id in", values, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdNotIn(List<String> values) {
			addCriterion("provider_id not in", values, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdBetween(String value1, String value2) {
			addCriterion("provider_id between", value1, value2, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdNotBetween(String value1, String value2) {
			addCriterion("provider_id not between", value1, value2, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdIsNull() {
			addCriterion("location_id is null");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdIsNotNull() {
			addCriterion("location_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdEqualTo(String value) {
			addCriterion("location_id =", value, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdNotEqualTo(String value) {
			addCriterion("location_id <>", value, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdGreaterThan(String value) {
			addCriterion("location_id >", value, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdGreaterThanOrEqualTo(String value) {
			addCriterion("location_id >=", value, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdLessThan(String value) {
			addCriterion("location_id <", value, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdLessThanOrEqualTo(String value) {
			addCriterion("location_id <=", value, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdLike(String value) {
			addCriterion("location_id like", value, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdNotLike(String value) {
			addCriterion("location_id not like", value, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdIn(List<String> values) {
			addCriterion("location_id in", values, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdNotIn(List<String> values) {
			addCriterion("location_id not in", values, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdBetween(String value1, String value2) {
			addCriterion("location_id between", value1, value2, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andLocationIdNotBetween(String value1, String value2) {
			addCriterion("location_id not between", value1, value2, "locationId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIsNull() {
			addCriterion("team is null");
			return (Criteria) this;
		}
		
		public Criteria andTeamIsNotNull() {
			addCriterion("team is not null");
			return (Criteria) this;
		}
		
		public Criteria andTeamEqualTo(String value) {
			addCriterion("team =", value, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamNotEqualTo(String value) {
			addCriterion("team <>", value, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamGreaterThan(String value) {
			addCriterion("team >", value, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamGreaterThanOrEqualTo(String value) {
			addCriterion("team >=", value, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamLessThan(String value) {
			addCriterion("team <", value, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamLessThanOrEqualTo(String value) {
			addCriterion("team <=", value, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamLike(String value) {
			addCriterion("team like", value, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamNotLike(String value) {
			addCriterion("team not like", value, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamIn(List<String> values) {
			addCriterion("team in", values, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamNotIn(List<String> values) {
			addCriterion("team not in", values, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamBetween(String value1, String value2) {
			addCriterion("team between", value1, value2, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamNotBetween(String value1, String value2) {
			addCriterion("team not between", value1, value2, "team");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdIsNull() {
			addCriterion("team_id is null");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdIsNotNull() {
			addCriterion("team_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdEqualTo(String value) {
			addCriterion("team_id =", value, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdNotEqualTo(String value) {
			addCriterion("team_id <>", value, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdGreaterThan(String value) {
			addCriterion("team_id >", value, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdGreaterThanOrEqualTo(String value) {
			addCriterion("team_id >=", value, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdLessThan(String value) {
			addCriterion("team_id <", value, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdLessThanOrEqualTo(String value) {
			addCriterion("team_id <=", value, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdLike(String value) {
			addCriterion("team_id like", value, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdNotLike(String value) {
			addCriterion("team_id not like", value, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdIn(List<String> values) {
			addCriterion("team_id in", values, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdNotIn(List<String> values) {
			addCriterion("team_id not in", values, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdBetween(String value1, String value2) {
			addCriterion("team_id between", value1, value2, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andTeamIdNotBetween(String value1, String value2) {
			addCriterion("team_id not between", value1, value2, "teamId");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedIsNull() {
			addCriterion("date_created is null");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedIsNotNull() {
			addCriterion("date_created is not null");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedEqualTo(Date value) {
			addCriterion("date_created =", value, "dateCreated");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedNotEqualTo(Date value) {
			addCriterion("date_created <>", value, "dateCreated");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedGreaterThan(Date value) {
			addCriterion("date_created >", value, "dateCreated");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedGreaterThanOrEqualTo(Date value) {
			addCriterion("date_created >=", value, "dateCreated");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedLessThan(Date value) {
			addCriterion("date_created <", value, "dateCreated");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedLessThanOrEqualTo(Date value) {
			addCriterion("date_created <=", value, "dateCreated");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedIn(List<Date> values) {
			addCriterion("date_created in", values, "dateCreated");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedNotIn(List<Date> values) {
			addCriterion("date_created not in", values, "dateCreated");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedBetween(Date value1, Date value2) {
			addCriterion("date_created between", value1, value2, "dateCreated");
			return (Criteria) this;
		}
		
		public Criteria andDateCreatedNotBetween(Date value1, Date value2) {
			addCriterion("date_created not between", value1, value2, "dateCreated");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedIsNull() {
			addCriterion("date_edited is null");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedIsNotNull() {
			addCriterion("date_edited is not null");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedEqualTo(Date value) {
			addCriterion("date_edited =", value, "dateEdited");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedNotEqualTo(Date value) {
			addCriterion("date_edited <>", value, "dateEdited");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedGreaterThan(Date value) {
			addCriterion("date_edited >", value, "dateEdited");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedGreaterThanOrEqualTo(Date value) {
			addCriterion("date_edited >=", value, "dateEdited");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedLessThan(Date value) {
			addCriterion("date_edited <", value, "dateEdited");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedLessThanOrEqualTo(Date value) {
			addCriterion("date_edited <=", value, "dateEdited");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedIn(List<Date> values) {
			addCriterion("date_edited in", values, "dateEdited");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedNotIn(List<Date> values) {
			addCriterion("date_edited not in", values, "dateEdited");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedBetween(Date value1, Date value2) {
			addCriterion("date_edited between", value1, value2, "dateEdited");
			return (Criteria) this;
		}
		
		public Criteria andDateEditedNotBetween(Date value1, Date value2) {
			addCriterion("date_edited not between", value1, value2, "dateEdited");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedIsNull() {
			addCriterion("date_deleted is null");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedIsNotNull() {
			addCriterion("date_deleted is not null");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedEqualTo(Date value) {
			addCriterion("date_deleted =", value, "dateDeleted");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedNotEqualTo(Date value) {
			addCriterion("date_deleted <>", value, "dateDeleted");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedGreaterThan(Date value) {
			addCriterion("date_deleted >", value, "dateDeleted");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedGreaterThanOrEqualTo(Date value) {
			addCriterion("date_deleted >=", value, "dateDeleted");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedLessThan(Date value) {
			addCriterion("date_deleted <", value, "dateDeleted");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedLessThanOrEqualTo(Date value) {
			addCriterion("date_deleted <=", value, "dateDeleted");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedIn(List<Date> values) {
			addCriterion("date_deleted in", values, "dateDeleted");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedNotIn(List<Date> values) {
			addCriterion("date_deleted not in", values, "dateDeleted");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedBetween(Date value1, Date value2) {
			addCriterion("date_deleted between", value1, value2, "dateDeleted");
			return (Criteria) this;
		}
		
		public Criteria andDateDeletedNotBetween(Date value1, Date value2) {
			addCriterion("date_deleted not between", value1, value2, "dateDeleted");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table core.event_metadata
	 * @mbg.generated  Fri Apr 06 12:20:41 EAT 2018
	 */
	public static class Criterion {
		
		private String condition;
		
		private Object value;
		
		private Object secondValue;
		
		private boolean noValue;
		
		private boolean singleValue;
		
		private boolean betweenValue;
		
		private boolean listValue;
		
		private String typeHandler;
		
		public String getCondition() {
			return condition;
		}
		
		public Object getValue() {
			return value;
		}
		
		public Object getSecondValue() {
			return secondValue;
		}
		
		public boolean isNoValue() {
			return noValue;
		}
		
		public boolean isSingleValue() {
			return singleValue;
		}
		
		public boolean isBetweenValue() {
			return betweenValue;
		}
		
		public boolean isListValue() {
			return listValue;
		}
		
		public String getTypeHandler() {
			return typeHandler;
		}
		
		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}
		
		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}
		
		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}
		
		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}
		
		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.event_metadata
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 07 18:26:22 EAT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}