package org.opensrp.domain.postgres;

public class Event {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.event.id
	 * @mbg.generated  Fri Mar 09 15:24:01 EAT 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.event.json
	 * @mbg.generated  Fri Mar 09 15:24:01 EAT 2018
	 */
	private Object json;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.event.id
	 * @return  the value of core.event.id
	 * @mbg.generated  Fri Mar 09 15:24:01 EAT 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.event.id
	 * @param id  the value for core.event.id
	 * @mbg.generated  Fri Mar 09 15:24:01 EAT 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.event.json
	 * @return  the value of core.event.json
	 * @mbg.generated  Fri Mar 09 15:24:01 EAT 2018
	 */
	public Object getJson() {
		return json;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.event.json
	 * @param json  the value for core.event.json
	 * @mbg.generated  Fri Mar 09 15:24:01 EAT 2018
	 */
	public void setJson(Object json) {
		this.json = json;
	}
}