package org.opensrp.domain.postgres;

import java.util.ArrayList;
import java.util.List;

public class MultiMediaExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public MultiMediaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	protected abstract static class GeneratedCriteria {
		
		protected List<Criterion> criteria;
		
		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}
		
		public boolean isValid() {
			return criteria.size() > 0;
		}
		
		public List<Criterion> getAllCriteria() {
			return criteria;
		}
		
		public List<Criterion> getCriteria() {
			return criteria;
		}
		
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}
		
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}
		
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}
		
		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}
		
		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}
		
		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdIsNull() {
			addCriterion("case_id is null");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdIsNotNull() {
			addCriterion("case_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdEqualTo(String value) {
			addCriterion("case_id =", value, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdNotEqualTo(String value) {
			addCriterion("case_id <>", value, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdGreaterThan(String value) {
			addCriterion("case_id >", value, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
			addCriterion("case_id >=", value, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdLessThan(String value) {
			addCriterion("case_id <", value, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdLessThanOrEqualTo(String value) {
			addCriterion("case_id <=", value, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdLike(String value) {
			addCriterion("case_id like", value, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdNotLike(String value) {
			addCriterion("case_id not like", value, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdIn(List<String> values) {
			addCriterion("case_id in", values, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdNotIn(List<String> values) {
			addCriterion("case_id not in", values, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdBetween(String value1, String value2) {
			addCriterion("case_id between", value1, value2, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andCaseIdNotBetween(String value1, String value2) {
			addCriterion("case_id not between", value1, value2, "caseId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdIsNull() {
			addCriterion("provider_id is null");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdIsNotNull() {
			addCriterion("provider_id is not null");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdEqualTo(String value) {
			addCriterion("provider_id =", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdNotEqualTo(String value) {
			addCriterion("provider_id <>", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdGreaterThan(String value) {
			addCriterion("provider_id >", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdGreaterThanOrEqualTo(String value) {
			addCriterion("provider_id >=", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdLessThan(String value) {
			addCriterion("provider_id <", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdLessThanOrEqualTo(String value) {
			addCriterion("provider_id <=", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdLike(String value) {
			addCriterion("provider_id like", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdNotLike(String value) {
			addCriterion("provider_id not like", value, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdIn(List<String> values) {
			addCriterion("provider_id in", values, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdNotIn(List<String> values) {
			addCriterion("provider_id not in", values, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdBetween(String value1, String value2) {
			addCriterion("provider_id between", value1, value2, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andProviderIdNotBetween(String value1, String value2) {
			addCriterion("provider_id not between", value1, value2, "providerId");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeIsNull() {
			addCriterion("content_type is null");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeIsNotNull() {
			addCriterion("content_type is not null");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeEqualTo(String value) {
			addCriterion("content_type =", value, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeNotEqualTo(String value) {
			addCriterion("content_type <>", value, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeGreaterThan(String value) {
			addCriterion("content_type >", value, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeGreaterThanOrEqualTo(String value) {
			addCriterion("content_type >=", value, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeLessThan(String value) {
			addCriterion("content_type <", value, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeLessThanOrEqualTo(String value) {
			addCriterion("content_type <=", value, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeLike(String value) {
			addCriterion("content_type like", value, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeNotLike(String value) {
			addCriterion("content_type not like", value, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeIn(List<String> values) {
			addCriterion("content_type in", values, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeNotIn(List<String> values) {
			addCriterion("content_type not in", values, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeBetween(String value1, String value2) {
			addCriterion("content_type between", value1, value2, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andContentTypeNotBetween(String value1, String value2) {
			addCriterion("content_type not between", value1, value2, "contentType");
			return (Criteria) this;
		}
		
		public Criteria andFilePathIsNull() {
			addCriterion("file_path is null");
			return (Criteria) this;
		}
		
		public Criteria andFilePathIsNotNull() {
			addCriterion("file_path is not null");
			return (Criteria) this;
		}
		
		public Criteria andFilePathEqualTo(String value) {
			addCriterion("file_path =", value, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFilePathNotEqualTo(String value) {
			addCriterion("file_path <>", value, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFilePathGreaterThan(String value) {
			addCriterion("file_path >", value, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFilePathGreaterThanOrEqualTo(String value) {
			addCriterion("file_path >=", value, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFilePathLessThan(String value) {
			addCriterion("file_path <", value, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFilePathLessThanOrEqualTo(String value) {
			addCriterion("file_path <=", value, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFilePathLike(String value) {
			addCriterion("file_path like", value, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFilePathNotLike(String value) {
			addCriterion("file_path not like", value, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFilePathIn(List<String> values) {
			addCriterion("file_path in", values, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFilePathNotIn(List<String> values) {
			addCriterion("file_path not in", values, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFilePathBetween(String value1, String value2) {
			addCriterion("file_path between", value1, value2, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFilePathNotBetween(String value1, String value2) {
			addCriterion("file_path not between", value1, value2, "filePath");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryIsNull() {
			addCriterion("file_category is null");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryIsNotNull() {
			addCriterion("file_category is not null");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryEqualTo(String value) {
			addCriterion("file_category =", value, "fileCategory");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryNotEqualTo(String value) {
			addCriterion("file_category <>", value, "fileCategory");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryGreaterThan(String value) {
			addCriterion("file_category >", value, "fileCategory");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryGreaterThanOrEqualTo(String value) {
			addCriterion("file_category >=", value, "fileCategory");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryLessThan(String value) {
			addCriterion("file_category <", value, "fileCategory");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryLessThanOrEqualTo(String value) {
			addCriterion("file_category <=", value, "fileCategory");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryLike(String value) {
			addCriterion("file_category like", value, "fileCategory");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryNotLike(String value) {
			addCriterion("file_category not like", value, "fileCategory");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryIn(List<String> values) {
			addCriterion("file_category in", values, "fileCategory");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryNotIn(List<String> values) {
			addCriterion("file_category not in", values, "fileCategory");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryBetween(String value1, String value2) {
			addCriterion("file_category between", value1, value2, "fileCategory");
			return (Criteria) this;
		}
		
		public Criteria andFileCategoryNotBetween(String value1, String value2) {
			addCriterion("file_category not between", value1, value2, "fileCategory");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table core.multi_media
	 * @mbg.generated  Wed Mar 14 17:13:39 EAT 2018
	 */
	public static class Criterion {
		
		private String condition;
		
		private Object value;
		
		private Object secondValue;
		
		private boolean noValue;
		
		private boolean singleValue;
		
		private boolean betweenValue;
		
		private boolean listValue;
		
		private String typeHandler;
		
		public String getCondition() {
			return condition;
		}
		
		public Object getValue() {
			return value;
		}
		
		public Object getSecondValue() {
			return secondValue;
		}
		
		public boolean isNoValue() {
			return noValue;
		}
		
		public boolean isSingleValue() {
			return singleValue;
		}
		
		public boolean isBetweenValue() {
			return betweenValue;
		}
		
		public boolean isListValue() {
			return listValue;
		}
		
		public String getTypeHandler() {
			return typeHandler;
		}
		
		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}
		
		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}
		
		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}
		
		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}
		
		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.multi_media
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 09 18:03:53 EAT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}