package org.opensrp.domain.postgres;

public class MultiMedia {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.multi_media.id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.multi_media.document_id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	private String documentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.multi_media.case_id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	private String caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.multi_media.provider_id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	private String providerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.multi_media.content_type
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	private String contentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.multi_media.file_path
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	private String filePath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.multi_media.file_category
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	private String fileCategory;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.multi_media.id
	 * @return  the value of core.multi_media.id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.multi_media.id
	 * @param id  the value for core.multi_media.id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.multi_media.document_id
	 * @return  the value of core.multi_media.document_id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public String getDocumentId() {
		return documentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.multi_media.document_id
	 * @param documentId  the value for core.multi_media.document_id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public void setDocumentId(String documentId) {
		this.documentId = documentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.multi_media.case_id
	 * @return  the value of core.multi_media.case_id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.multi_media.case_id
	 * @param caseId  the value for core.multi_media.case_id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.multi_media.provider_id
	 * @return  the value of core.multi_media.provider_id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public String getProviderId() {
		return providerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.multi_media.provider_id
	 * @param providerId  the value for core.multi_media.provider_id
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.multi_media.content_type
	 * @return  the value of core.multi_media.content_type
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.multi_media.content_type
	 * @param contentType  the value for core.multi_media.content_type
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.multi_media.file_path
	 * @return  the value of core.multi_media.file_path
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public String getFilePath() {
		return filePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.multi_media.file_path
	 * @param filePath  the value for core.multi_media.file_path
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.multi_media.file_category
	 * @return  the value of core.multi_media.file_category
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public String getFileCategory() {
		return fileCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.multi_media.file_category
	 * @param fileCategory  the value for core.multi_media.file_category
	 * @mbg.generated  Fri Mar 23 09:39:36 EAT 2018
	 */
	public void setFileCategory(String fileCategory) {
		this.fileCategory = fileCategory;
	}
}