package org.opensrp.domain.postgres;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.stock.id
     *
     * @mbg.generated Wed Mar 07 18:26:22 EAT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.stock.json
     *
     * @mbg.generated Wed Mar 07 18:26:22 EAT 2018
     */
    private Object json;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.stock.id
     *
     * @return the value of core.stock.id
     *
     * @mbg.generated Wed Mar 07 18:26:22 EAT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.stock.id
     *
     * @param id the value for core.stock.id
     *
     * @mbg.generated Wed Mar 07 18:26:22 EAT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.stock.json
     *
     * @return the value of core.stock.json
     *
     * @mbg.generated Wed Mar 07 18:26:22 EAT 2018
     */
    public Object getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.stock.json
     *
     * @param json the value for core.stock.json
     *
     * @mbg.generated Wed Mar 07 18:26:22 EAT 2018
     */
    public void setJson(Object json) {
        this.json = json;
    }
}