package org.opensrp.domain.postgres;

public class ViewConfigurationMetadata {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.view_configuration_metadata.id
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.view_configuration_metadata.view_configuration_id
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    private Long viewConfigurationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.view_configuration_metadata.document_id
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    private String documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.view_configuration_metadata.identifier
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.view_configuration_metadata.server_version
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    private Long serverVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.view_configuration_metadata.id
     *
     * @return the value of core.view_configuration_metadata.id
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.view_configuration_metadata.id
     *
     * @param id the value for core.view_configuration_metadata.id
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.view_configuration_metadata.view_configuration_id
     *
     * @return the value of core.view_configuration_metadata.view_configuration_id
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    public Long getViewConfigurationId() {
        return viewConfigurationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.view_configuration_metadata.view_configuration_id
     *
     * @param viewConfigurationId the value for core.view_configuration_metadata.view_configuration_id
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    public void setViewConfigurationId(Long viewConfigurationId) {
        this.viewConfigurationId = viewConfigurationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.view_configuration_metadata.document_id
     *
     * @return the value of core.view_configuration_metadata.document_id
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.view_configuration_metadata.document_id
     *
     * @param documentId the value for core.view_configuration_metadata.document_id
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.view_configuration_metadata.identifier
     *
     * @return the value of core.view_configuration_metadata.identifier
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.view_configuration_metadata.identifier
     *
     * @param identifier the value for core.view_configuration_metadata.identifier
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.view_configuration_metadata.server_version
     *
     * @return the value of core.view_configuration_metadata.server_version
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    public Long getServerVersion() {
        return serverVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.view_configuration_metadata.server_version
     *
     * @param serverVersion the value for core.view_configuration_metadata.server_version
     *
     * @mbg.generated Mon Apr 23 10:29:52 EAT 2018
     */
    public void setServerVersion(Long serverVersion) {
        this.serverVersion = serverVersion;
    }
}