INSERT INTO anm_report.dim_anm (anmIdentifier) VALUES ('c');

INSERT INTO anm_report.dim_indicator (indicator) VALUES ('DPT');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('DPT_1');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('DPT_2');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('DPT_3');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('DPT_BOOSTER_2');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('HEP');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('OPV');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('MEASLES');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('BCG');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('ANC');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('ANC<12');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('LIVE_BIRTH');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('STILL_BIRTH');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('OCP');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('IUD');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('MALE_STERILIZATION');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('FEMALE_STERILIZATION');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('CONDOM');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('DMPA');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('FP_TRADITIONAL');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('LAM');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('TT');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('LBW');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('MTP<12');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('MTP>12');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('SPONTANEOUS_ABORTION');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('DELIVERY');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('INSTITUTIONAL_DELIVERY');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('BF_POST_BIRTH');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('WEIGHED_AT_BIRTH');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('ENM');
INSERT INTO anm_report.dim_indicator (indicator) VALUES ('NM');

INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT'), 40, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_1'), 40, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_2'), 40, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_3'), 40, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DPT_BOOSTER_2'), 40, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='HEP'), 50, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OPV'), 60, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MEASLES'), 45, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BCG'), 55, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC'), 50, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='ANC<12'), 60, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='OCP'), 40, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='IUD'), 50, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='MALE_STERILIZATION'), 60, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FEMALE_STERILIZATION'), 400, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='CONDOM'), 55, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='DMPA'), 10, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='FP_TRADITIONAL'), 10, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='LAM'), 10, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='TT'), 40, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='LIVE_BIRTH'), 200, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='INSTITUTIONAL_DELIVERY'), 200, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='BF_POST_BIRTH'), 200, '2012-03-26', '2013-03-25');
INSERT INTO anm_report.annual_target (anmIdentifier, indicator, target, start_date, end_date) VALUES ((SELECT ID FROM anm_report.dim_anm WHERE anmIdentifier='c'), (SELECT ID FROM anm_report.dim_indicator WHERE indicator='WEIGHED_AT_BIRTH'), 200, '2012-03-26', '2013-03-25');